name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Swift package, debug
      # Build strictly
      run: swift build -v -c debug --disable-automatic-resolution
    - name: Build Swift package, release
      # Build strictly
      run: swift build -v -c release --disable-automatic-resolution
    - name: Run tests
      run: swift test -v
